### ISSUE TITLE
Cannot find Taz.exe path

### ISSUE THREAD

**Issue by red9350** [MuxaJlbl4/Taz_Wanted_trainer_and_patcher#1]
Maybe the path variable is not set correctly. It should search for ".\Taz.exe" with the leading dot (meaning current directory).
![image](https://user-images.githubusercontent.com/16651290/140618397-a798adea-eb39-4070-9564-f684a382d81d.png)

An improvement could be a TextBox where we can paste the install directory

**Comment by MuxaJlbl4** [comment]
Ok, thanks) TextBox is already inplemented in current build, and will be in next release
Can you tell me your registry path to TazWanted Location variable?
Is it `\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Infogrames Interactive\TazWanted\Release` ?

**Comment by red9350** [comment]
Unfortunately i don't have that registry key

**Comment by MuxaJlbl4** [comment]
**Game Path** form implemented in [v3.0](https://github.com/MuxaJlbl4/Taz_Wanted_trainer_and_patcher/releases/tag/v3.0/)
