### ISSUE TITLE
Launching the game after patching without going through the launcher

### ISSUE THREAD

**Issue by antonio-padalino** [MuxaJlbl4/Taz_Wanted_trainer_and_patcher#2]
Hey there o/
First of all, a huge thank you for this tool: this was literally my favorite childhood game, and being able to replay it today with such improvements means so much to me!

A quick question: is there a way, after patching the game once, to directly launch the game without having to go through the launcher? I am trying to get the game working on Steam Deck, and both the installation of the game itself and the use of your patcher is pretty flawless. But for some reason everytime I run `Taz.exe` or `TazLauncher.exe` the launcher comes up with an error window reporting that `Taz.dat` is corrupted and the game rolls back at its default settings. But, If I run your tool and either do _patch and play_ or _patch_ first and then _settings_ > _shortcuts_ > _play_, the game launches without issues and with all tweaks applied. It looks like it is something related to re-opening the launcher, I believe. And I can say this behavior only applies on Steam Deck, while on both another Windows pc and Linux pc there is no such issue.
The solution for now is simply to go everytime through your patcher and either go _patch and play_ or _settings_ > _shortcuts_ > _play_, but being able to directly launch the game would be absolutely awesome.

Thank you again for your work!

**Comment by MuxaJlbl4** [comment]
Hello! Thank you for your feedback and experience)
Yes, you can start game without any launcher with `Launched` argument:
- `Taz.exe Launched`

Also you can create bat or shortcut with this argument

**Comment by antonio-padalino** [comment]
It works like charm, thank you! I can confirm that launching the game with the `Launched` argument (after patching once) I am able to avoid the issue I mentioned. Also works with no issues on Steam Deck in game mode.
